name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  breaking-changes-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: angular/dev-infra/github-actions/breaking-changes-label@7d469335a076a30f8153b1129897417759eb908f
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
